#!/usr/bin/env bash

wget -c https://download-a.akamaihd.net/files/media_publication/2d/sjjm_T_001_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/7d/sjjm_T_002_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/e1/sjjm_T_003_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/35/sjjm_T_004_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/a1/sjjm_T_005_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/49/sjjm_T_006_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/d0/sjjm_T_007_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/da/sjjm_T_008_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/6e/sjjm_T_009_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/f7/sjjm_T_010_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/3b/sjjm_T_011_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/f8/sjjm_T_012_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/f8/sjjm_T_013_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/fb/sjjm_T_014_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/0d/sjjm_T_015_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/73/sjjm_T_016_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/6e/sjjm_T_017_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/e1/sjjm_T_018_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/ac/sjjm_T_019_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/ac/sjjm_T_020_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/c6/sjjm_T_021_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/36/sjjm_T_022_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/73/sjjm_T_023_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/36/sjjm_T_024_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/ed/sjjm_T_025_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/b8/sjjm_T_026_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/56/sjjm_T_027_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/b5/sjjm_T_028_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/cd/sjjm_T_029_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/25/sjjm_T_030_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/5a/sjjm_T_031_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/57/sjjm_T_032_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/dd/sjjm_T_033_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/a6/sjjm_T_034_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/41/sjjm_T_035_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/8f/sjjm_T_036_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/83/sjjm_T_037_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/20/sjjm_T_038_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/49/sjjm_T_039_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/53/sjjm_T_040_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/a2/sjjm_T_041_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/00/sjjm_T_042_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/8c/sjjm_T_043_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/f4/sjjm_T_044_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/b6/sjjm_T_045_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/d0/sjjm_T_046_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/30/sjjm_T_047_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/b3/sjjm_T_048_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/ac/sjjm_T_049_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/57/sjjm_T_050_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/d2/sjjm_T_051_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/cc/sjjm_T_052_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/88/sjjm_T_053_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/41/sjjm_T_054_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/8e/sjjm_T_055_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/e5/sjjm_T_056_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/40/sjjm_T_057_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/84/sjjm_T_058_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/98/sjjm_T_059_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/89/sjjm_T_060_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/2c/sjjm_T_061_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/50/sjjm_T_062_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/bd/sjjm_T_063_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/1f/sjjm_T_064_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/23/sjjm_T_065_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/f2/sjjm_T_066_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/78/sjjm_T_067_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/dd/sjjm_T_068_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/21/sjjm_T_069_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/c9/sjjm_T_070_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/4c/sjjm_T_071_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/38/sjjm_T_072_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/47/sjjm_T_073_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/95/sjjm_T_074_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/3a/sjjm_T_075_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/7c/sjjm_T_076_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/b4/sjjm_T_077_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/94/sjjm_T_078_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/ff/sjjm_T_079_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/f2/sjjm_T_080_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/4c/sjjm_T_081_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/48/sjjm_T_082_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/76/sjjm_T_083_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/82/sjjm_T_084_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/eb/sjjm_T_085_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/e2/sjjm_T_086_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/7b/sjjm_T_087_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/09/sjjm_T_088_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/0b/sjjm_T_089_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/7b/sjjm_T_090_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/34/sjjm_T_091_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/c5/sjjm_T_092_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/b2/sjjm_T_093_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/4e/sjjm_T_094_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/0d/sjjm_T_095_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/61/sjjm_T_096_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/84/sjjm_T_097_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/ee/sjjm_T_098_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/97/sjjm_T_099_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/7d/sjjm_T_100_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/dd/sjjm_T_101_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/a8/sjjm_T_102_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/46/sjjm_T_103_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/28/sjjm_T_104_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/5a/sjjm_T_105_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/c9/sjjm_T_106_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/d8/sjjm_T_107_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/b9/sjjm_T_108_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/39/sjjm_T_109_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/4d/sjjm_T_110_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/e4/sjjm_T_111_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/96/sjjm_T_112_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/3c/sjjm_T_113_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/ea/sjjm_T_114_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/f2/sjjm_T_115_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/e1/sjjm_T_116_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/f7/sjjm_T_117_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/e9/sjjm_T_118_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/40/sjjm_T_119_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/a2/sjjm_T_120_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/61/sjjm_T_121_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/01/sjjm_T_122_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/14/sjjm_T_123_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/06/sjjm_T_124_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/78/sjjm_T_125_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/c8/sjjm_T_126_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/bd/sjjm_T_127_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/6c/sjjm_T_128_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/74/sjjm_T_129_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/dd/sjjm_T_130_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/20/sjjm_T_131_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/60/sjjm_T_132_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/a6/sjjm_T_133_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/cb/sjjm_T_134_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/ee/sjjm_T_135_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/9a/sjjm_T_136_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/b2/sjjm_T_137_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/d3/sjjm_T_138_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/6f/sjjm_T_139_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/17/sjjm_T_140_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/29/sjjm_T_141_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/53/sjjm_T_142_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/48/sjjm_T_143_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/b4/sjjm_T_144_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/ef/sjjm_T_145_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/df/sjjm_T_146_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/90/sjjm_T_147_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/36/sjjm_T_148_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/a3/sjjm_T_149_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/8d/sjjm_T_150_r480P.mp4
wget -c https://download-a.akamaihd.net/files/media_publication/cf/sjjm_T_151_r480P.mp4
